theme: jekyll-theme-minimal
title: My Little Site
description: Site micut facut pentru Alexandra ca sa ii arat cat de mult tin la ea
        Si daca tot suntem la automatica, era pacat sa nu fac un site=))))
